export const HANDLE_MONTHLY_INPUT_CHANGE = "HANDLE_MONTHLY_INPUT_CHANGE";
export const HANDLE_MONTHLY_OTHER_SPEND_CHANGE =
  "HANDLE_MONTHLY_OTHER_SPEND_CHANGE";
export const HANDLE_APARTMENT_COST_CHANGE = "HANDLE_APARTMENT_COST_CHANGE";
export const HANDLE_FOOD_COST_CHANGE = "HANDLE_FOOD_COST_CHANGE";
export const HANDLE_INTERNET_COST_CHANGE = "HANDLE_INTERNET_COST_CHANGE";
export const HANDLE_TRAVEL_COST_CHANGE = "HANDLE_TRAVEL_COST_CHANGE";
