export const HANDLE_MONTHLY_INPUT_CHANGE = "HANDLE_MONTHLY_INPUT_CHANGE";
export const HANDLE_DELETE_EXPENSE_ITEM = "HANDLE_DELETE_EXPENSE_ITEM";
export const HANDLE_ADD_EXPENSE_ITEM = "HANDLE_ADD_EXPENSE_ITEM";
export const HANDLE_CHANGE_SINGLE_EXPENSE_NAME =
  "HANDLE_CHANGE_SINGLE_EXPENSE_NAME";
export const HANDLE_CHANGE_SINGLE_EXPENSE_COST =
  "HANDLE_CHANGE_SINGLE_EXPENSE_COST";
