export const HANDLE_MONTHLY_INPUT_CHANGE = "HANDLE_MONTHLY_INPUT_CHANGE";

export const HANDLE_DELETE_EXPENSE_ITEM = "HANDLE_DELETE_EXPENSE_ITEM";
export const HANDLE_ADD_EXPENSE_ITEM = "HANDLE_ADD_EXPENSE_ITEM";
export const HANDLE_CHANGE_SINGLE_EXPENSE_NAME =
  "HANDLE_CHANGE_SINGLE_EXPENSE_NAME";
export const HANDLE_CHANGE_SINGLE_EXPENSE_COST =
  "HANDLE_CHANGE_SINGLE_EXPENSE_COST";
export const HANDLE_SET_EXPENSES_ITEMS = "HANDLE_SET_EXPENSES_ITEMS";

export const HANDLE_USER_LOGIN = "HANDLE_USER_LOGIN";
export const HANDLE_USER_LOGOUT = "HANDLE_USER_LOGOUT";
export const HANDLE_USER_SIGNUP = "HANDLE_USER_SIGNUP";
export const HANDLE_LOADED_STATE_CHANGE = "HANDLE_LOADED_STATE_CHANGE";

export const HANDLE_ERROR_STATUS_CHANGE = "HANDLE_ERROR_STATUS_CHANGE";
